export const manualSections = [
  { key: 'gettingStarted', icon: 'rocket-outline' },
  { key: 'dashboardOverview', icon: 'grid-outline' },
  { key: 'profileAccountMenu', icon: 'person-circle-outline' },
  { key: 'wallets', icon: 'wallet-outline' },
  { key: 'currenciesBaseCurrency', icon: 'cash-outline' },
  { key: 'categoriesSubcategories', icon: 'pricetags-outline' },
  { key: 'records', icon: 'receipt-outline' },
  { key: 'addingIncome', icon: 'trending-up-outline' },
  { key: 'addingExpenses', icon: 'trending-down-outline' },
  { key: 'transfers', icon: 'swap-horizontal-outline' },
  { key: 'currencyExchange', icon: 'repeat-outline' },
  { key: 'loansDebt', icon: 'swap-vertical-outline' },
  { key: 'investments', icon: 'bar-chart-outline' },
  { key: 'budgets', icon: 'speedometer-outline' },
  { key: 'goals', icon: 'flag-outline' },
  { key: 'reportsDateRanges', icon: 'calendar-outline' },
  { key: 'reportInsights', icon: 'analytics-outline' },
  { key: 'exportsBackup', icon: 'download-outline' },
  { key: 'importingBackup', icon: 'cloud-upload-outline' },
  { key: 'themesAurora', icon: 'color-palette-outline' },
  { key: 'notifications', icon: 'notifications-outline' },
  { key: 'privacyLocalData', icon: 'lock-closed-outline' },
  { key: 'troubleshooting', icon: 'construct-outline' },
  { key: 'apkPlayProtect', icon: 'shield-checkmark-outline' },
  { key: 'updatingSafely', icon: 'download-outline' },
] as const;
