import type { ThemePreset } from '../types';

export type ColorSchemeName = 'light' | 'dark';

export interface AppTheme {
  scheme: ColorSchemeName;
  cardStyle: 'flat' | 'soft' | 'glass';
  buttonStyle: 'solid' | 'tonal';
  badgeStyle: 'soft' | 'outline';
  density: 'compact' | 'comfortable';
  recommendedIconStyle: 'line' | 'filled';
  chartPalette: string[];
  elevation: {
    card: number;
    sheet: number;
  };
  colors: {
    background: string;
    surface: string;
    surfaceElevated: string;
    text: string;
    textMuted: string;
    border: string;
    primary: string;
    primaryDark: string;
    secondary: string;
    accent: string;
    success: string;
    danger: string;
    warning: string;
    tabInactive: string;
    shadow: string;
  };
  spacing: (value: number) => number;
  radius: {
    sm: number;
    md: number;
    lg: number;
  };
}

function makeTheme(
  scheme: ColorSchemeName,
  colors: AppTheme['colors'],
  style: Partial<Pick<AppTheme, 'cardStyle' | 'buttonStyle' | 'badgeStyle' | 'density' | 'recommendedIconStyle' | 'chartPalette'>> = {}
): AppTheme {
  return {
    scheme,
    cardStyle: style.cardStyle ?? (scheme === 'dark' ? 'glass' : 'soft'),
    buttonStyle: style.buttonStyle ?? (scheme === 'dark' ? 'tonal' : 'solid'),
    badgeStyle: style.badgeStyle ?? 'soft',
    density: style.density ?? 'compact',
    recommendedIconStyle: style.recommendedIconStyle ?? 'line',
    chartPalette: style.chartPalette ?? [colors.primary, colors.success, colors.danger, colors.warning, colors.secondary, colors.accent],
    elevation: {
      card: scheme === 'dark' ? 1 : 2,
      sheet: 8,
    },
    colors,
    spacing: (value: number) => value * 8,
    radius: {
      sm: 6,
      md: 8,
      lg: 14,
    },
  };
}

export const themes: Record<ThemePreset, AppTheme> = {
  light: makeTheme('light', {
    background: '#F7F8FC',
    surface: '#FFFFFF',
    surfaceElevated: '#F1F4FA',
    text: '#171821',
    textMuted: '#6D7182',
    border: '#E5E9F2',
    primary: '#16A7A0',
    primaryDark: '#087B78',
    secondary: '#5E6AD2',
    accent: '#FF8A4C',
    success: '#16A34A',
    danger: '#E5484D',
    warning: '#F5A524',
    tabInactive: '#9197A8',
    shadow: '#16213E',
  }),
  dark: makeTheme('dark', {
    background: '#101217',
    surface: '#191C23',
    surfaceElevated: '#20242D',
    text: '#F7F8FC',
    textMuted: '#A6ADBD',
    border: '#2D333F',
    primary: '#2DD4BF',
    primaryDark: '#14B8A6',
    secondary: '#8B9CFF',
    accent: '#FFB86B',
    success: '#4ADE80',
    danger: '#FB7185',
    warning: '#FACC15',
    tabInactive: '#737B8C',
    shadow: '#000000',
  }),
  emeraldLight: makeTheme('light', {
    background: '#F1FBF6',
    surface: '#FFFFFF',
    surfaceElevated: '#E8F8EF',
    text: '#123226',
    textMuted: '#5D766B',
    border: '#CFEBDD',
    primary: '#0F9F6E',
    primaryDark: '#08754F',
    secondary: '#10B981',
    accent: '#F59E0B',
    success: '#16A34A',
    danger: '#DC2626',
    warning: '#D97706',
    tabInactive: '#7A9388',
    shadow: '#073B2A',
  }),
  oceanLight: makeTheme('light', {
    background: '#F2FAFF',
    surface: '#FFFFFF',
    surfaceElevated: '#DFF3FF',
    text: '#102A43',
    textMuted: '#58708A',
    border: '#BFE3F7',
    primary: '#0284C7',
    primaryDark: '#075985',
    secondary: '#38BDF8',
    accent: '#7C3AED',
    success: '#16A34A',
    danger: '#DC2626',
    warning: '#D97706',
    tabInactive: '#7594A8',
    shadow: '#0B3552',
  }),
  sunsetLight: makeTheme('light', {
    background: '#FFF7F1',
    surface: '#FFFFFF',
    surfaceElevated: '#FFE8D8',
    text: '#352016',
    textMuted: '#7C5F52',
    border: '#F4D2C0',
    primary: '#F97316',
    primaryDark: '#C2410C',
    secondary: '#EF4444',
    accent: '#F59E0B',
    success: '#16A34A',
    danger: '#DC2626',
    warning: '#D97706',
    tabInactive: '#A1887A',
    shadow: '#4C1D0D',
  }),
  royalLight: makeTheme('light', {
    background: '#F7F4FF',
    surface: '#FFFFFF',
    surfaceElevated: '#EEE7FF',
    text: '#251547',
    textMuted: '#6B5A88',
    border: '#DCD0FB',
    primary: '#7C3AED',
    primaryDark: '#5B21B6',
    secondary: '#A855F7',
    accent: '#0EA5E9',
    success: '#16A34A',
    danger: '#DC2626',
    warning: '#D97706',
    tabInactive: '#85759F',
    shadow: '#2E1065',
  }),
  sakuraLight: makeTheme('light', {
    background: '#FFF5F8',
    surface: '#FFFFFF',
    surfaceElevated: '#FFE4EE',
    text: '#3B1724',
    textMuted: '#8B6270',
    border: '#F7C9D8',
    primary: '#DB2777',
    primaryDark: '#9D174D',
    secondary: '#F472B6',
    accent: '#0EA5E9',
    success: '#16A34A',
    danger: '#E11D48',
    warning: '#D97706',
    tabInactive: '#A87988',
    shadow: '#4A1228',
  }),
  coffeeLight: makeTheme('light', {
    background: '#FBF5EF',
    surface: '#FFFFFF',
    surfaceElevated: '#F1E2D2',
    text: '#2F2117',
    textMuted: '#7B6658',
    border: '#E6D0BD',
    primary: '#9A5C2E',
    primaryDark: '#6B3B19',
    secondary: '#C08457',
    accent: '#0F766E',
    success: '#15803D',
    danger: '#B91C1C',
    warning: '#B45309',
    tabInactive: '#998474',
    shadow: '#3B2414',
  }),
  goldLight: makeTheme('light', {
    background: '#FBF7EF',
    surface: '#FFFFFF',
    surfaceElevated: '#F4E7CB',
    text: '#2C2417',
    textMuted: '#776B5A',
    border: '#E5D6B8',
    primary: '#B88900',
    primaryDark: '#8A6500',
    secondary: '#637A46',
    accent: '#C05621',
    success: '#15803D',
    danger: '#B91C1C',
    warning: '#B7791F',
    tabInactive: '#9A8B73',
    shadow: '#4A3210',
  }),
  jadeLight: makeTheme('light', {
    background: '#F2FBF8',
    surface: '#FFFFFF',
    surfaceElevated: '#DDF6EC',
    text: '#12372E',
    textMuted: '#5C7D73',
    border: '#BEE8D8',
    primary: '#008C6E',
    primaryDark: '#00624D',
    secondary: '#15A08A',
    accent: '#D4AF37',
    success: '#16A34A',
    danger: '#DC2626',
    warning: '#C99700',
    tabInactive: '#71958B',
    shadow: '#063D32',
  }),
  lavenderLight: makeTheme('light', {
    background: '#F8F5FF',
    surface: '#FFFFFF',
    surfaceElevated: '#EEE9FF',
    text: '#2F2551',
    textMuted: '#71658B',
    border: '#DCD4F7',
    primary: '#8B5CF6',
    primaryDark: '#6D28D9',
    secondary: '#C084FC',
    accent: '#14B8A6',
    success: '#16A34A',
    danger: '#DC2626',
    warning: '#D97706',
    tabInactive: '#8A7EA1',
    shadow: '#312E81',
  }),
  coralLight: makeTheme('light', {
    background: '#FFF6F4',
    surface: '#FFFFFF',
    surfaceElevated: '#FFE2DC',
    text: '#3B1D1A',
    textMuted: '#84615D',
    border: '#F7C9C0',
    primary: '#F05D5E',
    primaryDark: '#BE3638',
    secondary: '#FB7185',
    accent: '#0EA5E9',
    success: '#16A34A',
    danger: '#DC2626',
    warning: '#D97706',
    tabInactive: '#A57973',
    shadow: '#4B1718',
  }),
  slateLight: makeTheme('light', {
    background: '#F5F5F5',
    surface: '#FFFFFF',
    surfaceElevated: '#EEEEEE',
    text: '#1F2933',
    textMuted: '#667085',
    border: '#D9DEE7',
    primary: '#4B5563',
    primaryDark: '#111827',
    secondary: '#6B7280',
    accent: '#0EA5E9',
    success: '#15803D',
    danger: '#B91C1C',
    warning: '#B45309',
    tabInactive: '#8A94A6',
    shadow: '#111827',
  }),
  emeraldDark: makeTheme('dark', {
    background: '#08130D',
    surface: '#102015',
    surfaceElevated: '#1B3323',
    text: '#F1F8F3',
    textMuted: '#A6C5AE',
    border: '#294A33',
    primary: '#65A30D',
    primaryDark: '#3F6212',
    secondary: '#22C55E',
    accent: '#FACC15',
    success: '#4ADE80',
    danger: '#FB7185',
    warning: '#FBBF24',
    tabInactive: '#78957F',
    shadow: '#000000',
  }),
  oceanDark: makeTheme('dark', {
    background: '#071923',
    surface: '#0D2633',
    surfaceElevated: '#123445',
    text: '#E8F7FB',
    textMuted: '#9CC6D3',
    border: '#1B4659',
    primary: '#18B7CF',
    primaryDark: '#0E7C92',
    secondary: '#38BDF8',
    accent: '#2DD4BF',
    success: '#34D399',
    danger: '#FB7185',
    warning: '#FBBF24',
    tabInactive: '#75A3B1',
    shadow: '#000000',
  }),
  sunsetDark: makeTheme('dark', {
    background: '#190D08',
    surface: '#28150D',
    surfaceElevated: '#3A1E11',
    text: '#FFF5EE',
    textMuted: '#E3B39B',
    border: '#57301E',
    primary: '#FB923C',
    primaryDark: '#EA580C',
    secondary: '#F97316',
    accent: '#FACC15',
    success: '#4ADE80',
    danger: '#FB7185',
    warning: '#FBBF24',
    tabInactive: '#B58A74',
    shadow: '#000000',
  }),
  royalDark: makeTheme('dark', {
    background: '#151020',
    surface: '#211832',
    surfaceElevated: '#2C2142',
    text: '#FBF7FF',
    textMuted: '#C6B8DA',
    border: '#3D3154',
    primary: '#A78BFA',
    primaryDark: '#7C3AED',
    secondary: '#F0ABFC',
    accent: '#FBBF24',
    success: '#4ADE80',
    danger: '#FB7185',
    warning: '#FACC15',
    tabInactive: '#9587AA',
    shadow: '#000000',
  }),
  sakuraDark: makeTheme('dark', {
    background: '#180A12',
    surface: '#28101B',
    surfaceElevated: '#3A1828',
    text: '#FFF1F7',
    textMuted: '#E6ACC2',
    border: '#57233A',
    primary: '#F472B6',
    primaryDark: '#DB2777',
    secondary: '#FB7185',
    accent: '#38BDF8',
    success: '#4ADE80',
    danger: '#FB7185',
    warning: '#FBBF24',
    tabInactive: '#B88498',
    shadow: '#000000',
  }),
  coffeeDark: makeTheme('dark', {
    background: '#130F0B',
    surface: '#211A14',
    surfaceElevated: '#30251A',
    text: '#FFF8F0',
    textMuted: '#CDB9A4',
    border: '#4A3828',
    primary: '#C08457',
    primaryDark: '#92400E',
    secondary: '#D6A15F',
    accent: '#7DD3FC',
    success: '#86EFAC',
    danger: '#FDA4AF',
    warning: '#FDE68A',
    tabInactive: '#9A826B',
    shadow: '#000000',
  }),
  goldDark: makeTheme('dark', {
    background: '#0F0E0A',
    surface: '#1B1810',
    surfaceElevated: '#272216',
    text: '#FFF8E1',
    textMuted: '#C9B98A',
    border: '#3D3520',
    primary: '#FACC15',
    primaryDark: '#CA8A04',
    secondary: '#F59E0B',
    accent: '#FFFFFF',
    success: '#84CC16',
    danger: '#F87171',
    warning: '#FBBF24',
    tabInactive: '#9B8C5B',
    shadow: '#000000',
  }),
  jadeDark: makeTheme('dark', {
    background: '#06130F',
    surface: '#0D221B',
    surfaceElevated: '#14352B',
    text: '#ECFFF8',
    textMuted: '#9CCABB',
    border: '#1F4C3F',
    primary: '#10B981',
    primaryDark: '#047857',
    secondary: '#2DD4BF',
    accent: '#D4AF37',
    success: '#4ADE80',
    danger: '#FB7185',
    warning: '#FBBF24',
    tabInactive: '#76A79A',
    shadow: '#000000',
  }),
  lavenderDark: makeTheme('dark', {
    background: '#100D1D',
    surface: '#1B1630',
    surfaceElevated: '#282047',
    text: '#F8F5FF',
    textMuted: '#BFB1DF',
    border: '#3C3261',
    primary: '#C084FC',
    primaryDark: '#9333EA',
    secondary: '#A78BFA',
    accent: '#2DD4BF',
    success: '#4ADE80',
    danger: '#FB7185',
    warning: '#FBBF24',
    tabInactive: '#9182B3',
    shadow: '#000000',
  }),
  coralDark: makeTheme('dark', {
    background: '#17070A',
    surface: '#260D13',
    surfaceElevated: '#3A111B',
    text: '#FFF1F2',
    textMuted: '#F0A8B4',
    border: '#5B1F2C',
    primary: '#E11D48',
    primaryDark: '#9F1239',
    secondary: '#FB7185',
    accent: '#FBBF24',
    success: '#4ADE80',
    danger: '#F43F5E',
    warning: '#FACC15',
    tabInactive: '#AA7180',
    shadow: '#000000',
  }),
  slateDark: makeTheme('dark', {
    background: '#080D18',
    surface: '#111827',
    surfaceElevated: '#1E293B',
    text: '#F8FAFC',
    textMuted: '#A7B4C8',
    border: '#26364F',
    primary: '#60A5FA',
    primaryDark: '#2563EB',
    secondary: '#38BDF8',
    accent: '#FBBF24',
    success: '#4ADE80',
    danger: '#F87171',
    warning: '#FACC15',
    tabInactive: '#74839B',
    shadow: '#000000',
  }),
};

export const themeOptions: Array<{ value: ThemePreset | 'system'; labelKey: string; accent: string }> = [
  { value: 'system', labelKey: 'settings.system', accent: '#64748B' },
  { value: 'light', labelKey: 'settings.light', accent: themes.light.colors.primary },
  { value: 'dark', labelKey: 'settings.dark', accent: themes.dark.colors.primary },
  { value: 'emeraldLight', labelKey: 'settings.emeraldLight', accent: themes.emeraldLight.colors.primary },
  { value: 'oceanLight', labelKey: 'settings.oceanLight', accent: themes.oceanLight.colors.primary },
  { value: 'sunsetLight', labelKey: 'settings.sunsetLight', accent: themes.sunsetLight.colors.primary },
  { value: 'royalLight', labelKey: 'settings.royalLight', accent: themes.royalLight.colors.primary },
  { value: 'sakuraLight', labelKey: 'settings.sakuraLight', accent: themes.sakuraLight.colors.primary },
  { value: 'coffeeLight', labelKey: 'settings.coffeeLight', accent: themes.coffeeLight.colors.primary },
  { value: 'goldLight', labelKey: 'settings.goldLight', accent: themes.goldLight.colors.primary },
  { value: 'jadeLight', labelKey: 'settings.jadeLight', accent: themes.jadeLight.colors.primary },
  { value: 'lavenderLight', labelKey: 'settings.lavenderLight', accent: themes.lavenderLight.colors.primary },
  { value: 'coralLight', labelKey: 'settings.coralLight', accent: themes.coralLight.colors.primary },
  { value: 'slateLight', labelKey: 'settings.slateLight', accent: themes.slateLight.colors.primary },
  { value: 'emeraldDark', labelKey: 'settings.emeraldDark', accent: themes.emeraldDark.colors.primary },
  { value: 'oceanDark', labelKey: 'settings.oceanDark', accent: themes.oceanDark.colors.primary },
  { value: 'sunsetDark', labelKey: 'settings.sunsetDark', accent: themes.sunsetDark.colors.primary },
  { value: 'royalDark', labelKey: 'settings.royalDark', accent: themes.royalDark.colors.primary },
  { value: 'sakuraDark', labelKey: 'settings.sakuraDark', accent: themes.sakuraDark.colors.primary },
  { value: 'coffeeDark', labelKey: 'settings.coffeeDark', accent: themes.coffeeDark.colors.primary },
  { value: 'goldDark', labelKey: 'settings.goldDark', accent: themes.goldDark.colors.primary },
  { value: 'jadeDark', labelKey: 'settings.jadeDark', accent: themes.jadeDark.colors.primary },
  { value: 'lavenderDark', labelKey: 'settings.lavenderDark', accent: themes.lavenderDark.colors.primary },
  { value: 'coralDark', labelKey: 'settings.coralDark', accent: themes.coralDark.colors.primary },
  { value: 'slateDark', labelKey: 'settings.slateDark', accent: themes.slateDark.colors.primary },
];
